### ISSUE TITLE
Divine Rune Pouch Bug

### ISSUE THREAD

**Issue by mastersuleman** [salverrs/Remaining-Casts#1]
Doesn't seem to show number of casts left when using a divine rune pouch.

e.g.
![image](https://user-images.githubusercontent.com/18666249/214374762-a3835316-e7e4-4e5d-b125-ea14ac073e37.png)

**Comment by salverrs** [comment]
Thanks for reporting this! This is actually a bug caused by combo runes not being detected in rune pouches. Now fixed in adaba94f6fe6155998489ed36c946c8ef7cb9e4c. I've submitted a new [PR](https://github.com/runelite/plugin-hub/pull/3821) so hopefully the update will be available soon.

**Comment by mastersuleman** [comment]
Ah alright thanks man! Love the plugin

**Comment by salverrs** [comment]
This has now been fixed. Thanks, appreciate it!
